services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  coinbase-feeder:
    image: coinbase-feeder
    container_name: coinbase-feeder
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis

  forex-agent:
    image: forex-agent
    container_name: forex-agent
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CURRENCIES=BTC,ETH
      - REDIS_HOST=redis
      - DEBUG=y